version: "3.9"
services:
  kalamba-app:
    image: kalamba-app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://kalamba-app:8080/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "8080:8080"
    networks:
      - app_net
    depends_on:
      - mysql-db


  mysql-db:
    image: mysql:8
    networks:
      - app_net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kalamba
    ports:
      - "3307:3306"

networks:
  app_net:
    driver: bridge

